// automatically generated by the FlatBuffers compiler, do not modify

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Coin struct {
	_tab flatbuffers.Table
}

func GetRootAsCoin(buf []byte, offset flatbuffers.UOffsetT) *Coin {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Coin{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Coin) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Coin) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Coin) Denom() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Coin) Amount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Coin) MutateAmount(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func CoinStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CoinAddDenom(builder *flatbuffers.Builder, denom flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(denom), 0)
}
func CoinAddAmount(builder *flatbuffers.Builder, amount int64) {
	builder.PrependInt64Slot(1, amount, 0)
}
func CoinEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
