// automatically generated by the FlatBuffers compiler, do not modify

package users

const (
	KeyTypeEd25519 = 1
	KeyTypeSecp256k1 = 2
)

var EnumNamesKeyType = map[int]string{
	KeyTypeEd25519:"Ed25519",
	KeyTypeSecp256k1:"Secp256k1",
}

