// automatically generated by the FlatBuffers compiler, do not modify

package users

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PubKey struct {
	_tab flatbuffers.Table
}

func GetRootAsPubKey(buf []byte, offset flatbuffers.UOffsetT) *PubKey {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PubKey{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PubKey) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PubKey) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PubKey) Type() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PubKey) MutateType(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *PubKey) Key(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PubKey) KeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PubKey) KeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PubKeyStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PubKeyAddType(builder *flatbuffers.Builder, type_ int8) {
	builder.PrependInt8Slot(0, type_, 0)
}
func PubKeyAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func PubKeyStartKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PubKeyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
